import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bdy}>
        <main className={styles.main}>
          <h1>Home workout</h1>
          <h4 className={styles.begin}>BEGINNER</h4>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/absbeginner.jpg"
              height={137}
              width={275}
            />
          </div>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/chestworkout.jpeg"
              height={137}
              width={275}
            />
          </div>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/armwork.jpeg"
              height={137}
              width={275}
            />
          </div>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/legwork.jpeg"
              height={137}
              width={275}
            />
          </div>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/backwork.jpeg"
              height={137}
              width={275}
            />
          </div>
          <h4 className={styles.int}>INTERMEDIATE</h4>
          <div className={styles.cad} class="card">
            <Image
              style={{ borderRadius: "8.5px" }}
              src="/absbeginner.jpg"
              height={137}
              width={275}
            />
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <h4 className={styles.adv}>ADVANCED</h4>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              <Image
                style={{ borderRadius: "8.5px" }}
                src="/absbeginner.jpg"
                height={137}
                width={275}
              />
            </div>
            <div className={styles.cad} class="card">
              discover more workout
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
